### ISSUE TITLE
Command check expo tickets hangs

### ISSUE THREAD

**Issue by eightyfive** [YieldStudio/laravel-expo-notifier#19]
Simply running `php artisan expo:tickets:check` hangs.

**Comment by eightyfive** [comment]
Now I understand why: As long as there are tickets in database, command/job will keep checking.

But.

Since `InvalidExpoToken` event listener [does not delete the ticket](https://github.com/YieldStudio/laravel-expo-notifier/blob/main/src/Listeners/DeleteInvalidExpoToken.php) in DB, it will run forever?

**Comment by dtangdev** [comment]
Hello, this issue seems to be fixed by removing the json_decode issue.
Thank you very much :)
