### ISSUE TITLE
Deprecation of FCM legacy API

### ISSUE THREAD

**Issue by eightyfive** [YieldStudio/laravel-expo-notifier#28]
Context:
https://expo.dev/blog/expo-adds-support-for-fcm-http-v1-api

Is there a plan to support the `?useFcmV1=true` URL param?

**Comment by Brune04** [comment]
I've just manually adjusted vendor/yieldstudio/laravel-expo-notifier/src/ExpoNotificationsService.php to add ?useFcmV1=true to the SEND_NOTIFICATION_ENDPOINT variable to cover this right now.

After doing this, it appears that everything works properly. The only issue is when you use shouldBatch your notification icon does not show up on Android. It just shows a blank circle
